config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'teachers/signup' => 'teachers#new'
  resources :teachers do
    resources :classrooms
  end

  resources :assignments

  get 'students/signup' => 'students#new'
  resources :students

  get 'students/:id/class_assignments/:id', :to => 'students#class_assignments'

  resources :classroom_students

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	validates :name, presence: true

	has_many   :questions
	has_many   :pair_assignments
	belongs_to :classroom
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	has_many   :classroom_students
	has_many   :students, through: :classroom_students
	has_many   :assignments
	belongs_to :teacher


end

app/models/classroom_student.rb
class ClassroomStudent < ActiveRecord::Base
	belongs_to :classroom
	belongs_to :student
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	validates :content, presence: true

	belongs_to :sender, class_name: "Student"
	belongs_to :receiver, class_name: "Student"
	belongs_to :assignment
end

app/models/pair_assignment.rb
class PairAssignment < ActiveRecord::Base
	belongs_to :student_one, class_name: "Student"
	belongs_to :student_two, class_name: "Student"
	belongs_to :assignment

	def students
		return [self.student_one, self.student_two]
	end
end

app/models/student.rb
class Student < ActiveRecord::Base
validates :name, :email, :password_digest, presence: true
 validates :email, uniqueness: true

has_many :classroom_students
has_many :classrooms, through: :classroom_students

has_many :student_ones, class_name: "PairAssignment", source: :student_one, foreign_key: "student_one_id"
has_many :student_twos, class_name: "PairAssignment", source: :student_two, foreign_key: "student_two_id"

has_many :sent_feedbacks, class_name: "Feedback", source: :sender, foreign_key: "sender_id"
 has_many :received_feedbacks, class_name: "Feedback", source: :receiver, foreign_key: "receiver_id"

 def pair_assignments
  PairAssignment.where("pair_assignments.student_one_id = #{self.id} OR pair_assignments.student_two_id = #{self.id}")
 end

 has_secure_password #not encrypting password
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :name, :email, :password_digest, presence: true
	validates :email, uniqueness: true

	has_many :classrooms

  has_secure_password #not encrypting password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include AuthenticationConcern

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :find_assignment_params, only: [:show]

  def index
  end

  def show
    p "*" * 100
    p params
    p "*" * 100
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.create(assignment_params)
    redirect_to @assignment
  end

  private
  def find_assignment_params
    @assignment = Assignment.find(params[:id])
  end

  def assignment_params
    params.require(:assignment).permit(:name, :content, :classroom_id)
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :find_classroom_params, only: [:show, :edit, :update, :destroy]

  def index

  end

  def show
    @teacher = current_teacher
    @classroom_student = ClassroomStudent.new
    @students = Student.all
  end

  def new
    @classroom = Classroom.new
    @teacher = current_teacher
  end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @classroom = @teacher.classrooms.new(classroom_params)

    if @classroom.save
      redirect_to teacher_classroom_path(@teacher, @classroom)
    else
      @error = @classroom.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_classroom_params
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:name, :teacher_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = Teacher.where(email: params[:session][:email]).first || Student.where(email: params[:session][:email]).first

    if @user && @user.class.to_s == "Teacher" && (@user.password_digest == params[:session][:password_digest])
      session[:user_id] = @user.id
      session[:teacher] = true
      session[:student] = false

      redirect_to teacher_path(@user)
    elsif @user && @user.class.to_s == "Student" && (@user.password_digest == params[:session][:password_digest])
      session[:user_id] = @user.id
      session[:student] = true
      session[:teacher] = false

      redirect_to student_path(@user)
    else
      @signin_error = "Username/Password invalid. Please try again."
      # checkout Hartl Ch.8 for implementing flash msgs to catch session errors
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      session[:user_id] = @student.id
      session[:student] = true
      session[:teacher] = false

      redirect_to students_path
    else
      render 'new'
    end
  end

  def show
    if current_student
      @student = current_student
      @classes = current_student.classrooms
    else
      @student = Student.find(params[:id])
      @classes = @student.classrooms
    end
  end

  def class_assignments
    @student = current_student
    # class_assignments = Assignment.where(classroom_id: params[:id])
    @student_class_assignments = @student.pair_assignments.where(classroom_id: params[:id])

    # class_assignments.each do |assignment|
    #   @student_class_assignments << PairAssignment.where(student_one_id: current_student.id, assignment_id: assignment.id)
    #   @student_class_assignments << PairAssignment.where(student_two_id: current_student.id, assignment_id: assignment.id)
    # end

    p "*" * 20
    p @student_class_assignments
    p "*" * 20


    respond_to do |format|
      format.html {render partial: 'class_assignments', locals: {student_class_assignments: @student_class_assignments}}
      # format.json {render json: @student_class_assignments}
    end
  end


  private

  def student_params
    params.require(:student).permit(:name, :email, :password_digest)
  end
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  def index

  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      session[:user_id] = @teacher.id
      # redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:username, :password)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :find_teachers, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = Teacher.all
  end

  def show
    @classrooms = Classroom.where(teacher_id: @teacher.id)
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      session[:user_id] = @teacher.id
      session[:teacher] = true
      session[:student] = false

      redirect_to teacher_path(@teacher)
    else
      render 'new'
    end
  end

  private

  def find_teachers
    @teacher = Teacher.find(session[:user_id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :password_digest)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classroom_students_helper.rb
module ClassroomStudentsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignments/new.html.erb
<div class="container">
  <div class="row">
    <h1>Create New Assignment</h1>
    <br>
  </div>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-group">
        <%= form_for @assignment do |f| %>
          <%= f.label "Name" %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label "Questions" %>
          <%= f.text_field :content, class: "form-control" %>

          <%= f.hidden_field :classroom_id, value: params[:classroom] %>

          <br>
          <%= f.submit "Create Assignment", class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/assignments/show.html.erb
<div id="assignment">
  <div class="text-hero">
    <div class="container">
      <div class="row">
        <h2><%= @assignment.name %></h2>
      </div>
    </div>
  </div>
</div>

<section>
  <div class="container">
    <div class="row text-center">
      <h3>Instructions & Questions</h3>
      <%= instant_hangout hangout_type: 'moderated', lang: :en %>
      <br>
      <div class="col-sm-4 col-sm-offset-4">
        <%= @assignment.content %>
      </div>
    </div>
  </div>
</section>

app/views/classrooms/index.html.erb
I'm on clasroom index

app/views/classrooms/new.html.haml
= form_for [@teacher, @teacher.classrooms.build], method: :post do |f|
  = f.label "Name"
  = f.text_field :name

  = f.hidden_field :teacher_id, :value => current_teacher.id

  = f.submit 'Create Class', class: 'btn btn-default'

app/views/classrooms/show.html.erb
<div id="classroom">
  <div class="text-hero">
    <div class="container">
      <div class="row">
        <h2><%= @classroom.name %></h2>
      </div>
    </div>
  </div>
</div>

<section>
  <div class="container">
    <div class="row text-center center-block">
      <h2>Students</h2>
      <% @classroom.students.each do |student| %>
        <div class="col-xs-3">
          <div class="student-block">
            <!-- image placeholder -->
          </div>
          <br>
          <%= link_to(student_path(student.id)) do %>
            <p><%= student.name %></p>
          <% end %>

          <br>
        </div>
      <% end %>
    </div>
    <div class="row text-center center-block">
      <h2>Assignments</h2>
      <br><br>
      <% @classroom.assignments.each do |assignment| %>
        <div class="col-xs-3">
          <div class="assignment-block">
            <%= link_to(assignment_path(assignment.id)) do %>
              <h4><%= assignment.name.capitalize %></h4>
            <% end %>
          </div>
          <br>
        </div>
      <% end %>
    </div>
    <div class="row text-center">
      <%= link_to "Create Assignments", new_assignment_path({:assignment => @assignment, :teacher => @teacher, :classroom => @classroom}), class: "btn btn-class" %>
    </div>
  </div>
</section>

app/views/students/_class_assignments.html.erb
<div class="row text-center center-block">
  <br>
  <h1>Assignments</h1>
  <% student_class_assignments.each do |assignment| %>
    <div class="col-xs-3">
      <div class="assignment-block">
        <% if assignment %>
          <%= link_to(assignment_path(assignment.assignment_id), blank: :true) do %>
            <h4><%= Assignment.find(assignment.assignment_id).name.capitalize %></h4>
          <% end %>
        <% end %>
      </div>
      <br>
    </div>
  <% end %>
</div>

app/views/students/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if current_student %>
        <h1>Welcome <%= current_student.name %></h1>
      <% else %>
        <h1>Welcome Students</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      <% end %>
    </div>
  </div>
  <% if current_student %>
    <% current_student.classrooms.each_slice(3) do |name| %>
      <div class="row">
        <br><br>
        <% name.each do |classname| %>
          <div class="col-xs-4">
            <div class="class-block">
              <h2><%= classname.name %></h2>
              <p><%= classname.description %></p>
              <a href="#" class="btn btn-class text-right">View Class</a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row text-center">
      <div class="col-xs-6">
        <div class=" Student Sign In">
          <%= link_to 'Sign In', signin_path, class: "btn btn-class" %>
        </div>
      </div>

      <div class="col-xs-6">
        <div class="Student Sign Up">
          <%= link_to 'Sign Up', students_signup_path, class: "btn btn-class" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<div class="container">
  <div class="row">
    <h1>Student Sign Up</h1>
    <br>
  </div>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-group">
        <%= form_for @student do |f| %>
          <%= f.label "Name" %>
          <%= f.text_field :name, class: "form-control" %>

          <%= f.label "Email" %>
          <%= f.text_field :email, class: "form-control" %>

          <%= f.label "Password" %>
          <%= f.password_field :password_digest, class: "form-control" %>
          <br>
          <%= f.submit 'Sign Up', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/pair_assignment.html.haml
.container
  .row
    .col-xs-12.text-center
      - if current_student
        %h1= current_student.username
        = link_to 'Sign Out!', signout_path, method: :delete, class: 'btn btn-default'
      - else
        %h1 Student Sign Up
        = link_to 'Sign Up!', students_signup_path, class: 'btn btn-default'
        %h1 Student Sign In
        = link_to 'Sign In!', signin_path, class: 'btn btn-default'

  .row
    .col-md-4.text-center
      %h1 Assignment
      %h2= "Students: #{@studentone} & #{studenttwo}"

  .row
    .col-md-4.text-center
      %h1 Question(s):
      %div= @question

  .row
    .col-md-4.text-center
      .assignment_firepad
        .userlist
        .firepad
  .row
    .col-md-4.text-center
      .answer
      %input{:type => "Submit"}
            %a.btn
              %i.icon-search.icon-white

app/views/students/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= @student.name %></h1>
      <br>

      <div class="col-sm-4 col-sm-offset-4 text-center">
        <select id="classlist">
          <option>Select A Class</option>
        <% @classes.each do |clss| %>
          <option value="<%= clss.id %>"><%= clss.name %></option>
        <% end %>
        </select>
      </div>
      <div class="class_assignments"></div>
    </div>
  </div>
</div>