config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'teachers/signup' => 'teachers#new'
  resources :teachers do
    resources :classrooms
  end

  resources :assignments

  get 'students/signup' => 'students#new'
  resources :students

  get 'students/:id/class_assignments/:id', :to => 'students#class_assignments'

  resources :classroom_students

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	validates :name, presence: true

	has_many   :questions
	has_many   :pair_assignments
	belongs_to :classroom
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
	has_many   :classroom_students
	has_many   :students, through: :classroom_students
	has_many   :assignments
	belongs_to :teacher


end

app/models/classroom_student.rb
class ClassroomStudent < ActiveRecord::Base
	belongs_to :classroom
	belongs_to :student
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	validates :content, presence: true

	belongs_to :sender, class_name: "Student"
	belongs_to :receiver, class_name: "Student"
	belongs_to :assignment
end

app/models/pair_assignment.rb
class PairAssignment < ActiveRecord::Base
	belongs_to :student_one, class_name: "Student"
	belongs_to :student_two, class_name: "Student"
	belongs_to :assignment

	def students
		return [self.student_one, self.student_two]
	end
end

app/models/student.rb
class Student < ActiveRecord::Base
validates :name, :email, :password_digest, presence: true
 validates :email, uniqueness: true

has_many :classroom_students
has_many :classrooms, through: :classroom_students

has_many :student_ones, class_name: "PairAssignment", source: :student_one, foreign_key: "student_one_id"
has_many :student_twos, class_name: "PairAssignment", source: :student_two, foreign_key: "student_two_id"

has_many :sent_feedbacks, class_name: "Feedback", source: :sender, foreign_key: "sender_id"
 has_many :received_feedbacks, class_name: "Feedback", source: :receiver, foreign_key: "receiver_id"

 def pair_assignments
  PairAssignment.where("pair_assignments.student_one_id = #{self.id} OR pair_assignments.student_two_id = #{self.id}")
 end

 has_secure_password #not encrypting password
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :name, :email, :password_digest, presence: true
	validates :email, uniqueness: true

	has_many :classrooms

  has_secure_password #not encrypting password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include AuthenticationConcern

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :find_classroom_params, only: [:show, :edit, :update, :destroy]

  def index

  end

  def show
    @teacher = current_teacher
    @classroom_student = ClassroomStudent.new
    @students = Student.all
  end

  def new
    @classroom = Classroom.new
    @teacher = current_teacher
  end

  def create
    @teacher = Teacher.find(params[:teacher_id])
    @classroom = @teacher.classrooms.new(classroom_params)

    if @classroom.save
      redirect_to teacher_classroom_path(@teacher, @classroom)
    else
      @error = @classroom.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_classroom_params
    @classroom = Classroom.find(params[:id])
  end

  def classroom_params
    params.require(:classroom).permit(:name, :teacher_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = Teacher.where(email: params[:session][:email]).first || Student.where(email: params[:session][:email]).first

    if @user && @user.class.to_s == "Teacher" && (@user.password_digest == params[:session][:password_digest])
      session[:user_id] = @user.id
      session[:teacher] = true
      session[:student] = false

      redirect_to teacher_path(@user)
    elsif @user && @user.class.to_s == "Student" && (@user.password_digest == params[:session][:password_digest])
      session[:user_id] = @user.id
      session[:student] = true
      session[:teacher] = false

      redirect_to student_path(@user)
    else
      @signin_error = "Username/Password invalid. Please try again."
      # checkout Hartl Ch.8 for implementing flash msgs to catch session errors
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      session[:user_id] = @student.id
      session[:student] = true
      session[:teacher] = false

      redirect_to students_path
    else
      render 'new'
    end
  end

  def show
    if current_student
      @student = current_student
      @classes = current_student.classrooms
    else
      @student = Student.find(params[:id])
      @classes = @student.classrooms
    end
  end

  def class_assignments
    @student = current_student
    # class_assignments = Assignment.where(classroom_id: params[:id])
    @student_class_assignments = @student.pair_assignments.where(classroom_id: params[:id])

    # class_assignments.each do |assignment|
    #   @student_class_assignments << PairAssignment.where(student_one_id: current_student.id, assignment_id: assignment.id)
    #   @student_class_assignments << PairAssignment.where(student_two_id: current_student.id, assignment_id: assignment.id)
    # end

    p "*" * 20
    p @student_class_assignments
    p "*" * 20


    respond_to do |format|
      format.html {render partial: 'class_assignments', locals: {student_class_assignments: @student_class_assignments}}
      # format.json {render json: @student_class_assignments}
    end
  end


  private

  def student_params
    params.require(:student).permit(:name, :email, :password_digest)
  end
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  def index

  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      session[:user_id] = @teacher.id
      # redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:username, :password)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :find_teachers, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = Teacher.all
  end

  def show
    @classrooms = Classroom.where(teacher_id: @teacher.id)
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      session[:user_id] = @teacher.id
      session[:teacher] = true
      session[:student] = false

      redirect_to teacher_path(@teacher)
    else
      render 'new'
    end
  end

  private

  def find_teachers
    @teacher = Teacher.find(session[:user_id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :password_digest)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/classroom_students_helper.rb
module ClassroomStudentsHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_navbar.html.erb
<!-- Navigation -->
         <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
             <div class="container">
                 <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                         <i class="fa fa-bars"></i>
                     </button>
                     <a class="navbar-brand page-scroll" href="/">
                        <span class="light">Study Buddy</span>
                     </a>
                 </div>

                 <!-- Collect the nav links, forms, and other content for toggling -->
                 <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                     <ul class="nav navbar-nav">
                         <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                          <li class="hidden">
                             <a href="#page-top"></a>
                          </li>
                        <% if current_student %>
                          <li><a href="/students/<%= current_student.id %>">Hello, <%= current_student.name %></a></li>
                          <li><a href="/signout" data-method="delete">Logout</a></li>
                        <% elsif current_teacher %>
                          <li><a href="/teachers/<%= current_teacher.id %>">Hello, <%= current_teacher.name %></a></li>
                          <li><a href="/signout" data-method="delete">Logout</a></li>
                        <% else %>
                          <li class="signin"><a href="/signin">Sign In</a></li>
                        <% end %>
                     </ul>
                 </div>
                 <!-- /.navbar-collapse -->
             </div>
             <!-- /.container -->
         </nav>

app/views/welcome/index.html.erb
<div class="container">
  <section class="row">
    <h1>Study Buddy</h1>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </section>
</div>

<div id="student">
  <div class="text-hero">
    <div class="container">
      <div class="row">
        <h2><%= link_to 'Students', students_path %></h2>
      </div>
    </div>
  </div>
</div>

<div id="teacher">
  <div class="text-hero">
    <div class="container">
      <div class="row">
        <h2><%= link_to 'Teachers', teachers_path %></h2>
      </div>
    </div>
  </div>
</div>