config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'teachers/signup' => 'teachers#new'
  resources :teachers do
    resources :classrooms
  end

  resources :assignments

  get 'students/signup' => 'students#new'
  resources :students

  get 'students/:id/class_assignments/:id', :to => 'students#class_assignments'

  resources :classroom_students

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	validates :name, :email, :password_digest, presence: true
	validates :email, uniqueness: true

	has_many :classrooms

  has_secure_password #not encrypting password
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  def index

  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      session[:user_id] = @teacher.id
      # redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def teacher_params
    params.require(:teacher).permit(:username, :password)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :find_teachers, only: [:show, :edit, :update, :destroy]

  def index
    @teachers = Teacher.all
  end

  def show
    @classrooms = Classroom.where(teacher_id: @teacher.id)
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      session[:user_id] = @teacher.id
      session[:teacher] = true
      session[:student] = false

      redirect_to teacher_path(@teacher)
    else
      render 'new'
    end
  end

  private

  def find_teachers
    @teacher = Teacher.find(session[:user_id])
  end

  def teacher_params
    params.require(:teacher).permit(:name, :email, :password_digest)
  end

end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/teachers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Welcome Teachers</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>
  </div>
  <% if current_teacher %>

  <% else %>
    <div class="row text-center">
      <div class="col-xs-6">
        <div class=" Student Sign In">
          <%= link_to 'Sign In', signin_path, class: "btn btn-class" %>
        </div>
      </div>

      <div class="col-xs-6">
        <div class="Student Sign Up">
          <%= link_to 'Sign Up', teachers_signup_path, class: "btn btn-class" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/teachers/new.html.erb
<div class="container">
  <div class="row">
    <h1>Teacher Sign Up</h1>
    <br>
  </div>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-group">
        <%= form_for :session, url: signin_path do |f| %>
          <%= f.label "Email" %>
          <%= f.text_field :email, class: "form-control" %>

          <%= f.label "Password" %>
          <%= f.password_field :password_digest, class: "form-control" %>
          <br>
          <%= f.submit 'Sign In', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/teachers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% if current_teacher %>
        <h1>Welcome <%= current_teacher.name %></h1>
      <% else %>
        <h1>Welcome Teachers</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      <% end %>
    </div>
  </div>
  <% if current_teacher %>
    <% current_teacher.classrooms.each_slice(3) do |name| %>
      <div class="row">
        <br><br>
        <% name.each do |classname| %>
          <div class="col-xs-4">
            <div class="class-block">
              <h2><%= classname.name %></h2>
              <p><%= classname.description %></p>
              <a href="/teachers/<%= current_teacher.id %>/classrooms/<%= classname.id %>" class="btn btn-class text-right">View Class</a>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="row text-center">
      <div class="col-xs-6">
        <div class="Teacher Sign In">
          <%= link_to 'Sign In', signin_path, class: "btn btn-class" %>
        </div>
      </div>

      <div class="col-xs-6">
        <div class="Teacher Sign Up">
          <%= link_to 'Sign Up', teachers_signup_path, class: "btn btn-class" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/teachers/show.html.haml
.container
  .row
    .col-xs-12.text-center
      %h2= current_teacher.name
      = link_to 'Create Class', new_teacher_classroom_path(@teacher), class: "btn btn-default"
      /teachers/:id/classrooms/new
      /teachers/:teacher_id/classrooms/new

  - @classrooms.each_slice(4) do |classroom|
    .row
      - classroom.each do |classroom|
        .col-xs-3
          %h4= classroom.name